# Generated by Django 4.2 on 2023-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(blank=True, choices=[('V', 'verified'), ('U', 'unverified')], default='U', max_length=2)),
            ],
        ),
    ]
